server:
  port: 8088
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf-8
    username:
    password:
  profiles:
    active: properties
  jpa:
    hibernate:
      ddl-auto: none
  redis:
    host: localhost
    port: 6379
    password:

logging:
  config: classpath:config/logback.xml